[package]
name = "laminar-service"
version = "0.3.1"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0" }
hex-literal = "0.3.1"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"

frame-benchmarking = { version = "2.0.1" }
frame-system-rpc-runtime-api = { version = "2.0.1" }
pallet-transaction-payment-rpc-runtime-api = { version = "2.0.1" }
sc-basic-authorship = { version = "0.8.1" }
sc-chain-spec = { version = "2.0.1" }
sc-client-api = { version = "2.0.1" }
sc-consensus = { version = "0.8.1" }
sc-consensus-babe = { version = "0.8.1" }
sc-executor = { version = "0.8.1" }
sc-finality-grandpa = { version = "0.8.1" }
sc-network = { version = "0.8.1" }
sc-cli = { version = "0.8.1" }
sc-service = { version = "0.8.1" }
sc-telemetry = { version = "2.0.1" }
sc-transaction-pool = { version = "2.0.1" }
sp-api = { version = "2.0.1" }
sp-arithmetic = { version = "2.0.1" }
sp-block-builder = { version = "2.0.1" }
sp-blockchain = { version = "2.0.1" }
sp-consensus = { version = "0.8.1" }
sp-consensus-babe = { version = "0.8.1" }
sc-consensus-slots = { version = "0.8.1" }
sp-core = { version = "2.0.1" }
sp-finality-grandpa = { version = "2.0.1" }
sp-inherents = { version = "2.0.1" }
sp-offchain = { version = "2.0.1" }
sp-runtime = { version = "2.0.1" }
sp-session = { version = "2.0.1" }
sp-storage = { version = "2.0.1" }
sp-transaction-pool = { version = "2.0.1" }
sp-trie = { version = "2.0.1" }
sp-timestamp = { version = "2.0.1" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.8.1"}

cumulus-network = { git = "https://github.com/paritytech/cumulus" }
cumulus-service = { git = "https://github.com/paritytech/cumulus" }
cumulus-consensus = { git = "https://github.com/paritytech/cumulus" }

polkadot-primitives = { git = "https://github.com/paritytech/polkadot" }
polkadot-service = { git = "https://github.com/paritytech/polkadot" }

margin-protocol = { package="module-margin-protocol", path = "../../../modules/margin-protocol" }
synthetic-tokens = { package="module-synthetic-tokens", path = "../../../modules/synthetic-tokens" }
margin-protocol-rpc = { path = "../../../modules/margin-protocol/rpc" }
orml-oracle-rpc = { path = "../../../orml/oracle/rpc" }
synthetic-protocol-rpc = { path = "../../../modules/synthetic-protocol/rpc" }

dev-runtime = { path = "../../../runtime/dev" }
runtime-common = { path = "../../../runtime/common" }

laminar-primitives = { path = "../../../primitives" }
laminar-rpc = { path = "../../../rpc" }

[dev-dependencies]
sc-consensus-babe = { version = "0.8.1", features = ["test-helpers"] }

[features]
default = ["std"]
std = []
runtime-benchmarks = [
	"dev-runtime/runtime-benchmarks",
]
