[package]
name = "laminar-cli"
version = "0.3.1"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[dependencies]
log = "0.4.8"
structopt = "0.3.8"
codec = { package = 'parity-scale-codec', version = '1.0.0' }

sp-core = { version = "2.0.1", optional = true }
sc-cli = { version = "0.8.1", optional = true }
sc-service = { version = "0.8.1", optional = true }
sc-tracing = { version = "2.0.1" }
sp-runtime = { version = "2.0.1" }
frame-benchmarking-cli = { version = "2.0.1", optional = true }

cumulus-primitives = { git = "https://github.com/paritytech/cumulus" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot" }
polkadot-cli = { git = "https://github.com/paritytech/polkadot" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot" }

inspect = { package = "laminar-inspect", path = "../../../inspect" }
service = { package = "laminar-service", path = "../service", default-features = false, optional = true }

[build-dependencies]
substrate-build-script-utils = { version = "2.0.1", default-features = false }

[features]
default = ["wasmtime", "cli"]
wasmtime = [ "sc-cli/wasmtime" ]
cli = [
	"service",
	"sp-core",
	"sc-cli",
	"sc-service",
	"frame-benchmarking-cli",
]
runtime-benchmarks = [ "service/runtime-benchmarks" ]
